### ISSUE TITLE
Comma separated values

### ISSUE THREAD

**Issue by charliewilco** [charlespeters/stylelint-config-wilco#1]
from [Idiomatic.css](https://github.com/necolas/idiomatic-css)

> Long, comma-separated property values - such as collections of gradients or shadows - can be arranged across multiple lines in an effort to improve readability and produce more useful diffs. There are various formats that could be used; one example is shown below.

``` css
.selector {
    background-image:
        linear-gradient(#fff, #ccc),
        linear-gradient(#f3c, #4ec);
    box-shadow:
        1px 1px 1px #000,
        2px 2px 1px 1px #ccc inset;
}
```
